@echo off
echo .............................................................................
echo    This program converts the RCG/RCE output files LEVELS2 and OUTG11 into the
echo    input files ENLEV.DAT and TRANS.DAT for V.Azarov's IDEN program.
echo    See file CONV_OUT.HLP for help.
echo .............................................................................
conv_out_old.exe %1 %2 %3 %4 %5 %6 %7