@echo off
cls
echo .
echo                               Program RCN Mod 36k
echo           calculates single-configuration radial wavefunctions for a
echo                spherically symmetrized atom via one of the four
echo             homogeneous-differential-equation approximations to the
echo                               HARTREE-FOCK method
echo                                    ‹‹‹‹‹‹‹‹‹
echo                                    € START €
echo                                    ﬂﬂﬂﬂﬂﬂﬂﬂﬂ
call mark_time.bat "%~dp0rcn36k.exe"
