@echo off
cls
echo .
echo                                  Program RCN2k
echo              accepts radial wavefunctions from RCN and calculates
echo                     multiple-configuration radial integrals
echo                                    ‹‹‹‹‹‹‹‹‹
echo                                    € START €
echo                                    ﬂﬂﬂﬂﬂﬂﬂﬂﬂ
call mark_time.bat "%~dp0rcn2k.exe"
