#!/bin/bash
# Drive the ab-initio Cowan chain (RCN -> RCN2 -> RCG) on the FULL Mg I config
# basis -- Bob Kurucz's 122-config set (b1200{e,o}.com), generated by
# tools/gen_in36.py. This is the "completeness" experiment: match Bob's basis,
# then (separately) fit Bob-style with the HF ridge prior.
#
# Prereqs: build/build.sh, build/make_cfp.sh.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$HERE/.."
BIN="$ROOT/build/bin"; CFP="$ROOT/build/cfp"; EX="$ROOT/cowan_nist/extracted"
RUN="$HERE/mg1_full"
mkdir -p "$RUN"

# (re)generate Bob's full config deck unless one is already present
[ -f "$RUN/in36" ] || python3 "$ROOT/tools/gen_in36.py" --out "$RUN/in36"

cd "$RUN"
cp -f "$EX/work/IN2" IN2
cp -f "$CFP/FOR072" "$CFP/FOR073" "$CFP/FOR074" .
cp -f "$EX/code/SENIOR" .
echo "$RUN/" > cowan.cfg

echo "[1/3] RCN   ($(grep -c '^   12' in36) configs)"
"$BIN/rcn"  < /dev/null > rcn_run.log  2>&1
[ -f TAPE2N ] || ln -sf tape2n TAPE2N
echo "[2/3] RCN2"
"$BIN/rcn2" < /dev/null > rcn2_run.log 2>&1
echo "[3/3] RCG   (ab initio levels + gf)"
"$BIN/rcg"  < /dev/null > rcg_run.log  2>&1
cp -f OUTG11 OUTG11.abinitio
cp -f ING11  ING11.abinitio
cp -f OUTGINE OUTGINE.abinitio 2>/dev/null || true

python3 - <<'PY'
import sys; sys.path.insert(0,"../../tools")
from parse_cowan import parse_outg11
calc, lines = parse_outg11("OUTG11")
print(f"Done. {len(calc)} levels, {len(lines)} E1 lines (ab initio).")
PY
